### PR TITLE
Add title bar

### PR DESCRIPTION
**Pull request by owenwexler**

### CODE REVIEW

**Comment by claire-melbourne** [comment]
Will you post screen shot or gif?

**Comment by owenwexler** [comment]
My bad.

Screen Shot 2020-10-08 at 10 00 16 PM
Screen Shot 2020-10-08 at 10 00 27 PM

**Review by claire-melbourne — APPROVED** [review]
Looks great! Its fun to see how our different css approaches are similar and different but end up with basically the same effect!

**Comment by owenwexler** [comment]
Gotta love how there's 60909843509856 different ways to do everything in programming

**Pull request merged**
